name: date-range
type: php
docroot: ""
php_version: "8.2"
webserver_type: generic
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mariadb
    version: "10.4"
omit_containers: [db, ddev-ssh-agent]
use_dns_when_possible: true
composer_version: "2"
web_environment: []
corepack_enable: false
